const countryCodes = new Map();

countryCodes.set('United Arab Emirates', 'ae');
countryCodes.set('Argentina', 'ar');
countryCodes.set('Austria', 'at');
countryCodes.set('Australia', 'au');
countryCodes.set('Belgium', 'be');
countryCodes.set('Bulgaria', 'bg');
countryCodes.set('Brazil', 'br');
countryCodes.set('Canada', 'ca');
countryCodes.set('Switzerland', 'ch');
countryCodes.set('China', 'cn');
countryCodes.set('Colombia', 'co');
countryCodes.set('Cuba', 'cu');
countryCodes.set('Czechia', 'cz');
countryCodes.set('Germany', 'de');
countryCodes.set('Egypt', 'eg');
countryCodes.set('France', 'fr');
countryCodes.set('United Kingdom of Great Britain and Northern Ireland', 'gb');
countryCodes.set('Greece', 'gr');
countryCodes.set('Hong Kong', 'hk');
countryCodes.set('Hungary', 'hu');
countryCodes.set('Indonesia', 'id');
countryCodes.set('Ireland', 'ie');
countryCodes.set('Israel', 'il');
countryCodes.set('India', 'in');
countryCodes.set('Italy', 'it');
countryCodes.set('Japan', 'jp');
countryCodes.set('Korea', 'kr');
countryCodes.set('Lithuania', 'lt');
countryCodes.set('Latvia', 'lv');
countryCodes.set('Morocco', 'ma');
countryCodes.set('Mexico', 'mx');
countryCodes.set('Malaysia', 'my');
countryCodes.set('Nigeria', 'ng');
countryCodes.set('Netherlands', 'nl');
countryCodes.set('Norway', 'no');
countryCodes.set('New Zealand', 'nz');
countryCodes.set('Philippines', 'ph');
countryCodes.set('Poland', 'pl');
countryCodes.set('Portugal', 'pt');
countryCodes.set('Romania', 'ro');
countryCodes.set('Serbia', 'rs');
countryCodes.set('Russia', 'ru');
countryCodes.set('Saudi Arabia', 'sa');
countryCodes.set('Sweden', 'se');
countryCodes.set('Singapore', 'sg');
countryCodes.set('Slovenia', 'si');
countryCodes.set('Slovakia', 'sk');
countryCodes.set('Thailand', 'th');
countryCodes.set('Turkiye', 'tr');
countryCodes.set('Taiwan', 'tw');
countryCodes.set('Ukraine', 'ua');
countryCodes.set('United States', 'us');
countryCodes.set('Venezuela', 've');
countryCodes.set('South Africa', 'za');




module.exports = countryCodes;